### ISSUE TITLE
Custom fonts not working

### ISSUE THREAD

**Issue by MarksCode** [westmonroe/pdf-puppeteer#13]
I'm generating my pdf from markup which includes `<style>` tag inside. Inside the tag is a custom font: 

```
@font-face {
    font-family: 'my-font';
    src: url('http://myWebsite/my-font.woff') format('woff');
    font-weight: normal;
    font-style: normal;
}
```

Using that font face on an element does not work. My guess is that puppeteer generates the pdf before the font has a chance to load.

Does anyone know if there's a way around this?

**Comment by joehiggs** [comment]
There is an open pr that proposed a different way to load content, and I think it could possibly resolve this issue. I was waiting for the submitter to make a small change to the pr, but since I haven't heard back, I'll probably do it myself later this week. If you're looking to debug in the meantime, I would try forking the repo, looking at the way the page is rendered for remote content in the pr and seeing if that fixes the issue. Let me know if you have questions

**Comment by MarksCode** [comment]
Nice. Just checked it out, looks good!

**Comment by joehiggs** [comment]
Published a new version to npm with the aforementioned changes. Sounds like it got everything working for you? If so, the published npm version should work as well. Let me know if you still run into any issues, otherwise closing this issue for now. Thanks for submitting!

**Comment by MarksCode** [comment]
@joehiggs any reason why you use async? That's still not supported by a lot of people's servers. Can't use this package because of that... maybe we can have a fallback?

**Comment by joehiggs** [comment]
Async was just the default way that chrome recommends using puppeteer; however, it is possible to go without async as seen here: https://github.com/GoogleChrome/puppeteer/issues/829 
Feel free to submit a pr adding the option for the fallback, I won't be able to get to this for about a week or so

**Comment by joehiggs** [comment]
Closing issue and opening new issue with feature request for fallback version without use of `async`
